-- Array-backed re-implementation of the consensus attestation pipeline.
--
-- The Aeneas-generated `state_transition.process_attestations` runs at
-- O(A · V²) because every Vec push is `List.concat` (O(N)) and every Vec
-- index walks the list (O(i)).  We can't `attribute [implemented_by]` it
-- after the fact (Lean rejects retroactive overrides on imports), and the
-- generated module is regenerated by Aeneas, so editing it would be lost
-- on the next pull.  Instead this module exposes a parallel pipeline whose
-- entry point — `stateTransitionFast` — wraps the Aeneas linear-time pieces
-- (`process_slots`, `process_block_header`, `hash_tree_root_state`) with a
-- hand-rolled `processAttestationsFast` that converts every Vec we touch
-- into a Lean `Array`, runs the per-attestation logic in-place, and only
-- serialises back to Vec form once at the end.  Net cost falls from
-- O(A · V²) to O(A · V); this is what the FFI layer benchmarks.
import ConsensusLean4.Funs
import ConsensusLean4.Types
open Aeneas Aeneas.Std ethlambda_verification
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace ConsensusLean4.FastPath

instance : Inhabited types.H256 := ⟨types.H256.ZERO⟩

instance : Inhabited types.Checkpoint :=
  ⟨{ root := types.H256.ZERO, slot := 0#u64 }⟩

instance : Inhabited types.AttestationData :=
  ⟨{ slot := 0#u64, head := default, target := default, source := default }⟩

instance : Inhabited types.AggregatedAttestation :=
  ⟨{ aggregation_bits := alloc.vec.Vec.new Bool, data := default }⟩

/-! ## Vec ↔ Array bridges

Both directions are O(n) but otherwise allocation-free; the Array form is
what every inner loop manipulates. -/

@[inline] private def asArray {α : Type} (v : alloc.vec.Vec α) : Array α :=
  v.val.toArray

@[inline] private def fromArray {α : Type} (a : Array α) :
    Result (alloc.vec.Vec α) :=
  let xs := a.toList
  if h : xs.length ≤ Usize.max then
    .ok ⟨xs, h⟩
  else
    .fail .integerOverflow

/-! ## Read-only state snapshot used by every per-attestation step. -/

private structure AttestCtx where
  numValidators  : Nat
  historical     : Array types.H256
  justifiedSlots : Array Bool
  finalizedSlot  : Std.U64

@[inline] private def h256Eq (a b : types.H256) : Result Bool :=
  types.H256.Insts.CoreCmpPartialEqH256.eq a b

/-- Direct port of `state_transition.is_valid_vote` with Array indexing.
Mirrors the Aeneas predicate; we duplicate the logic instead of calling
the original because the original walks two Vecs per call. -/
private def voteIsValid
    (ctx : AttestCtx) (source target : types.Checkpoint) : Result Bool := do
  let finSlot : Nat := ctx.finalizedSlot.val
  -- A slot is `justified` if it's <= finalized (already final) or flagged
  -- in the rolling justifiedSlots window indexed at (slot - finalized - 1).
  let isJustified (slot : Nat) : Bool :=
    if slot ≤ finSlot then true
    else
      let idx := slot - finSlot - 1
      decide (idx < ctx.justifiedSlots.size) && ctx.justifiedSlots[idx]!
  let srcSlot : Nat := source.slot.val
  let tgtSlot : Nat := target.slot.val
  if !isJustified srcSlot then return false
  if isJustified tgtSlot then return false
  if ← types.H256.is_zero source.root then return false
  if ← types.H256.is_zero target.root then return false
  -- checkpoint_exists: the historical hash at that slot must equal the
  -- checkpoint's root (and the slot must be in range).
  let srcOk ←
    if srcSlot < ctx.historical.size then
      h256Eq ctx.historical[srcSlot]! source.root
    else
      pure false
  if !srcOk then return false
  let tgtOk ←
    if tgtSlot < ctx.historical.size then
      h256Eq ctx.historical[tgtSlot]! target.root
    else
      pure false
  if !tgtOk then return false
  if tgtSlot ≤ srcSlot then return false
  state_transition.slot_is_justifiable_after target.slot ctx.finalizedSlot

/-- Locate `target` inside `cells.map (·.1)` via linear scan. Returns
`cells.size` when not present. -/
private def lookupRoot
    (cells : Array (types.H256 × Array Bool)) (target : types.H256) :
    Result Nat := do
  let mut i := 0
  let mut found := cells.size
  while i < cells.size do
    if (← h256Eq cells[i]!.1 target) then
      found := i
      i := cells.size
    else
      i := i + 1
  return found

/-- Apply one attestation to the per-root vote bitmaps. Returns `none`
when the 2/3 threshold trips on the touched root, signalling the caller
to fall back to the Aeneas slow path so `try_finalize` runs unchanged. -/
private def stepAttestation
    (ctx : AttestCtx)
    (att : types.AggregatedAttestation)
    (cells : Array (types.H256 × Array Bool)) :
    Result (Option (Array (types.H256 × Array Bool))) := do
  if !(← voteIsValid ctx att.data.source att.data.target) then
    return some cells
  let mut next := cells
  let mut hit ← lookupRoot next att.data.target.root
  if hit = next.size then
    next := next.push (att.data.target.root, Array.replicate ctx.numValidators false)
  let bits := asArray att.aggregation_bits
  if bits.size > ctx.numValidators then
    -- Aeneas treats this as a no-op write path; matching that keeps parity.
    return some next
  let (root, votes0) := next[hit]!
  let mut votes := votes0
  let mut vi := 0
  while vi < bits.size do
    if bits[vi]! && vi < ctx.numValidators then
      votes := votes.set! vi true
    vi := vi + 1
  next := next.set! hit (root, votes)
  let mut yes := 0
  let mut k := 0
  while k < votes.size do
    if votes[k]! then yes := yes + 1
    k := k + 1
  if 3 * yes ≥ 2 * ctx.numValidators then
    return none
  return some next

/-! ## Flat ↔ unflattened justification representation.

Aeneas keeps the per-root vote bitmaps in two parallel Vecs: a `Vec H256`
with one zero-root sentinel followed by the actual roots, and a flat
`Vec Bool` of length `R · V` where row `r` holds the `V` votes for root
`r-1`. Working with that layout in the inner loop forces O(V) lookups
per write; the helpers below switch to a row-of-rows representation for
the hot path and serialise back at the end. -/

private def explodeJustifications
    (roots : Array types.H256) (flat : Array Bool) (V : Nat) :
    Array (types.H256 × Array Bool) := Id.run do
  let mut out : Array (types.H256 × Array Bool) := Array.mkEmpty roots.size
  let mut r := 0
  while r < roots.size do
    let votes := Array.ofFn (n := V) fun ⟨vi, _⟩ =>
      let idx := r * V + vi
      if idx < flat.size then flat[idx]! else false
    out := out.push (roots[r]!, votes)
    r := r + 1
  out

private def collapseJustifications
    (cells : Array (types.H256 × Array Bool)) (V : Nat) :
    Result (alloc.vec.Vec types.H256 × alloc.vec.Vec Bool) := do
  -- Aeneas prepends a zero-hash sentinel to the roots vector during
  -- serialisation; we mirror that here.
  let rootsArr : Array types.H256 :=
    (#[types.H256.ZERO] : Array types.H256).append (cells.map Prod.fst)
  let R := rootsArr.size
  let total := R * V
  let mut flat : Array Bool := Array.replicate total false
  let mut r := 0
  while r < cells.size do
    let (_, votes) := cells[r]!
    let rowStart := (r + 1) * V
    let mut vi := 0
    while vi < V do
      if vi < votes.size && votes[vi]! then
        let idx := rowStart + vi
        if idx < total then
          flat := flat.set! idx true
      vi := vi + 1
    r := r + 1
  let rootsVec ← fromArray rootsArr
  let flatVec ← fromArray flat
  return (rootsVec, flatVec)

/-! ## Public entry points. -/

/-- Array-backed counterpart to `state_transition.process_attestations`. -/
def processAttestationsFast
    (state : types.State)
    (attestations : alloc.vec.Vec types.AggregatedAttestation) :
    Result ((core.result.Result Unit state_transition.Error) × types.State) := do
  -- Aeneas explicitly rejects justifications_roots holding a zero hash;
  -- preserve that gate.
  let roots := asArray state.justifications_roots
  let mut zi := 0
  while zi < roots.size do
    if (← types.H256.is_zero roots[zi]!) then
      return (.Err state_transition.Error.ZeroHashInJustificationRoots, state)
    zi := zi + 1
  let V : Nat := state.validators.val.length
  let ctx : AttestCtx := {
    numValidators  := V
    historical     := asArray state.historical_block_hashes
    justifiedSlots := asArray state.justified_slots
    finalizedSlot  := state.latest_finalized.slot
  }
  let mut cells := explodeJustifications roots
    (asArray state.justifications_validators) V
  let atts := asArray attestations
  let mut bailed := false
  let mut i := 0
  while i < atts.size && !bailed do
    match ← stepAttestation ctx atts[i]! cells with
    | some c => cells := c
    | none   => bailed := true
    i := i + 1
  if bailed then
    state_transition.process_attestations state attestations
  else
    let (rootsVec, flatVec) ← collapseJustifications cells V
    return (.Ok (), { state with
      justifications_roots := rootsVec,
      justifications_validators := flatVec })

/-- `state_transition.process_block` with the attestation step swapped
for `processAttestationsFast`. The header step stays linear and Aeneas-
generated. -/
def processBlockFast
    (state : types.State) (block : types.Block) :
    Result ((core.result.Result Unit state_transition.Error) × types.State) := do
  let (r, s1) ← state_transition.process_block_header state block
  let cf ← core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | .Continue _ =>
    let (r1, s2) ← processAttestationsFast s1 block.body.attestations
    let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
    match cf1 with
    | .Continue _      => return (.Ok (), s2)
    | .Break residual  =>
      let r2 ← core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Unit (core.convert.FromSame state_transition.Error) residual
      return (r2, s2)
  | .Break residual =>
    let r1 ← core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      Unit (core.convert.FromSame state_transition.Error) residual
    return (r1, s1)

/-- `state_transition.state_transition` with the fast attestation path. -/
def stateTransitionFast
    (state : types.State) (block : types.Block) :
    Result ((core.result.Result Unit state_transition.Error) × types.State) := do
  let (r, s1) ← state_transition.process_slots state block.slot
  let cf ← core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | .Continue _ =>
    let (r1, s2) ← processBlockFast s1 block
    let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r1
    match cf1 with
    | .Continue _ =>
      let computed ← types.hash_tree_root_state s2
      let eq ← types.H256.Insts.CoreCmpPartialEqH256.eq block.state_root computed
      if eq then return (.Ok (), s2)
      else return (.Err state_transition.Error.StateRootMismatch, s2)
    | .Break residual =>
      let r2 ← core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Unit (core.convert.FromSame state_transition.Error) residual
      return (r2, s2)
  | .Break residual =>
    let r1 ← core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      Unit (core.convert.FromSame state_transition.Error) residual
    return (r1, s1)

end ConsensusLean4.FastPath
