-- This file was initialised from `FunsExternal_Template.lean` (generated by Aeneas).
-- [ethlambda_verification]: external functions.
-- The five `axiom` slots from the template are filled below with real Lean
-- implementations so the consensus model is computable end-to-end. M2 of the
-- FFI plan; required before stateTransitionFast can be linked into Rust.
-- `FunsExternal_Template.lean` is refreshed on every Aeneas run and remains
-- the canonical signature reference — diff it against this file to catch
-- upstream signature drift.
import Aeneas
import ConsensusLean4.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
open ethlambda_verification

/-- [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 389:43-389:52
    Name pattern: [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
def core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  (a b : Ordering) : Result Bool :=
  ok (a == b)

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
def core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)
  | .Ok t  => ok (.Continue t)
  | .Err e => ok (.Break (.Err e))

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
def
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)
  | .Ok i  => nomatch i
  | .Err e => do
    let f ← convertFromInst.from_ e
    ok (.Err f)

/-- [alloc::vec::{alloc::vec::Vec<T>}::clear]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2903:4-2903:27
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::clear]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::clear"]
def alloc.vec.Vec.clear
  {T : Type} (A : Type) (_v : alloc.vec.Vec T) : Result (alloc.vec.Vec T) :=
  ok ⟨[], by simp⟩

/-- [alloc::vec::{alloc::vec::Vec<T>}::is_empty]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2956:4-2956:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::is_empty]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::is_empty"]
def alloc.vec.Vec.is_empty
  {T : Type} (A : Type) (v : alloc.vec.Vec T) : Result Bool :=
  ok v.val.isEmpty
